apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-http-server"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "http-server.metaLabels" $ | nindent 4 }}
    app.kubernetes.io/component: "http-server"
data:
  {{- range $key, $val := .Values.environmentVariables.decoded }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{/*
  {{- if not (hasKey .Values.environmentVariables.decoded "APP_ENDPOINT") }}
  APP_ENDPOINT: "http://{{ $.Release.Name }}-http-server:80"
  {{- end }}
  */}}
