apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-http-server"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "http-server.metaLabels" $ | nindent 4 }}
    app.kubernetes.io/component: "http-server"
data:
  {{- range $key, $val := .Values.environmentVariables.encoded }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
