apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-http-server"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "http-server.metaLabels" $ | nindent 4 }}
    app.kubernetes.io/component: "http-server"
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") (.Values.service.clusterIP) }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (.Values.service.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: http
    targetPort: http
    port: 80
    {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    protocol: TCP
  selector:
    {{- include "http-server.matchLabels" $ | nindent 4 }}
    app.kubernetes.io/component: "http-server"
