version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: db0
    volumes:
    - type: volume
      source: postgres_data
      target: /var/lib/postgresql/data

  pgadmin:
    depends_on:
    - postgres
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
    - mode: host
      target: 80
      published: ${PGADMIN_PORT}
      protocol: tcp
    volumes:
    - type: bind
      # https://www.pgadmin.org/docs/pgadmin4/dev/export_import_servers.html
      source: ./pgadmin-servers.json
      # https://www.pgadmin.org/docs/pgadmin4/dev/container_deployment.html#mapped-files-and-directories
      target: /pgadmin4/servers.json
    - type: volume
      source: pgadmin_data
      target: /var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
