version: "3.8"
services:
  mailhog:
    image: mailhog/mailhog:latest
    entrypoint: |
      ash -ce "
        echo \"${MAILHOG_USER}:$$(MailHog bcrypt '${MAILHOG_PASSWORD}')\" > /home/mailhog/htpasswd
        exec MailHog -auth-file=/home/mailhog/htpasswd
      "
    ports:
    - mode: host
      target: 8025
      published: ${MAILHOG_PORT}
      protocol: tcp
