version: "3.8"
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
    - type: volume
      source: mongo_config
      target: /data/configdb
    - type: volume
      source: mongo_data
      target: /data/db

  mongo_express:
    depends_on:
    - mongo
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_EXPRESS_USER}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_EXPRESS_PASSWORD}"
    ports:
    - mode: host
      target: 8081
      published: ${MONGO_EXPRESS_PORT}
      protocol: tcp

volumes:
  mongo_config:
    driver: local
  mongo_data:
    driver: local
