version: "2.4"
services:
  rabbitmq:
    image: rabbitmq:management #:latest
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
    volumes:
    - type: volume
      source: rabbitmq_data
      target: /var/lib/rabbitmq
    ports:
    - ${RABBITMQ_MANAGEMENT_PORT}:15672

volumes:
  rabbitmq_data:
    driver: local
