version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management #:latest
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
    volumes:
    - type: volume
      source: rabbitmq_data
      target: /var/lib/rabbitmq
    ports:
    - mode: host
      target: 15672
      published: ${RABBITMQ_MANAGEMENT_PORT}
      protocol: tcp

volumes:
  rabbitmq_data:
    driver: local
