apiVersion: v1
kind: Secret
metadata:
  name: example-image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  # {
  #   "auths": {
  #     "https://index.docker.io/v1/": {
  #       "auth": "..."
  #     }
  #   }
  # }
  .dockerconfigjson: |
    ...
