---
apiVersion: v1
kind: Endpoints
metadata:
  name: example-external-service
subsets:
- addresses:
  - ip: 11.22.33.44
  ports:
  - name: http
    port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: example-external-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector: { }

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-external-service
spec:
  rules:
  - host: external-service.example.tld
    http:
      paths:
      - path: /
        backend:
          serviceName: example-external-service
          servicePort: http
