apiVersion: v1
kind: Secret
metadata:
  name: example-htpasswd-secret
type: Opaque
data:
  # Plain text:
  # myusername:mypassword

  # Password encrypted with the "openssl passwd -apr1" command:
  # myusername:$apr1$ns6c1HpR$YltFcSDMQJYDw0YKeVtdb.

  # Content encoded with the "echo 'myusername:$apr1$ns6c1HpR$YltFcSDMQJYDw0YKeVtdb.' | base64" command:
  auth: "bXl1c2VybmFtZTokYXByMSRuczZjMUhwUiRZbHRGY1NETVFKWUR3MFlLZVZ0ZGIuCg=="
