apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-npm-cache
  labels:
    volume: local-npm-cache
spec:
  storageClassName: manual
  capacity:
    storage: 10G
  accessModes:
  - ReadWriteOnce
  hostPath:
    type: Directory
    # $ npm config get cache
    # $ docker volume inspect local_npm_cache --format="{{ .Mountpoint }}"
    path: "/var/lib/docker/volumes/local_npm_cache/_data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-npm-cache
  labels:
    volume: local-npm-cache
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 10G
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      volume: local-npm-cache
